[package]
name = "ghp-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gh-pilot = { version = "0.1", path = "../gh-pilot" }
clap = {version = "3.2.16", features = ["derive", "env"] }
comfy-table = "6.0.0"
tokio = {version = "1.20.1", features = ["full"] }
hex = "0.4.3"
log = "0.4.17"
