[package]
name = "github"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.142", features = ["derive"] }
reqwest = { version = "0.11.11", features = ["json", "multipart"]}
thiserror = "1.0.32"
serde_json = "1.0.83"

[dev-dependencies]
tokio = {version = "1.20.1", features = ["full"] }
