---
## Test with multiple ruby images and frameworks
name: test

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby-image:
          - 'ruby:2.7'
          - 'ruby:2.6'
          - 'ruby:2.5'
          - 'ruby:2.4'
          - 'ruby:2.3'
          - 'jruby:9.2'
        framework:
          - 'rails-6.1'
          - 'rails-6.0'
          - 'rails-5.2'
          - 'sinatra-2.0'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
        # TODO: Change to elastic/...@current when https://github.com/elastic/apm-pipeline-library/pull/1979 is released
      - uses: reakaleek/apm-pipeline-library/.github/actions/docker-layer-caching@feature/docker-layer-caching-action-facade
        with:
          # {hash} must be included according to docs. https://github.com/marketplace/actions/docker-layer-caching
          # The key must be unique to every distinct matrix job
          key: docker-cache-${{ matrix.ruby-image }}-${{ matrix.framework }}-${{ github.workflow }}-{hash}
          restore-keys: |
            docker-cache-${{ matrix.ruby-image }}-${{ matrix.framework }}-${{ github.workflow }}-
      - name: Test ${{ matrix.ruby-image }}, ${{ matrix.framework }}
        env:
          RUBY_VERSION: ${{ matrix.ruby-image }}
        run: bin/dev --image=${{ matrix.ruby-image }} --frameworks=${{ matrix.framework }}
      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-results
          path: 'spec/junit-reports/**/*-junit.xml'
